<a href="https://colab.research.google.com/github/yrsf75h9mk-ctrl/AI-NLP-Study/blob/main/Day%2002_%EC%8B%A4%EC%8A%B5_%ED%85%90%EC%84%9C%20%EC%A1%B0%EC%9E%91%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2026.10.02
#멋쟁이 사자처럼
#02-02 텐서 조작하기(Tensor Manipulation)

In [2]:
#넘파이로 텐서 만들기
import numpy as np

In [ ]:
#1차원 텐서 만들기 (=벡터) vs 숫자 1개면 스칼라
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t(t의 차원):', t.ndim)
print('Shape of t(t의 크기):', t.shape)

Rank of t(t의 차원): 1
Shape of t(t의 크기): (7,)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])  #인덱스 사용
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) #슬라이스
print('t[:2] t[3:] =', t[:2], t[3:])  #생략하면 처음부터 또는 끝까지

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


In [ ]:
#2차원 행렬 = 2차원 텐서 만들기
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


In [4]:
#3. 파이토치 텐서 선언하기 (numpy와 유사하지만 더 나음)
import torch

In [ ]:
#1D with PyTorch (벡터)
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
#2D with PyTorch 2차원 텐서 행렬
t = torch.FloatTensor([[1.,2.,3.],
                      [4.,5.,6.],
                      [7.,8.,9.],
                      [10.,11.,12.]])
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])


In [ ]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
print(t[:-1
        , :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.


tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


In [ ]:
#브로드캐스팅
#행렬 계산시 자동으로 크기 맞춰줌

m1 = torch.FloatTensor([3,3])   #크기 (1.2)
m2 = torch.FloatTensor([2,2])
print(m1+m2)

tensor([5., 5.])


In [ ]:
#벡터 + 스칼라(숫자 하나)
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3]) #[3] 크기 (1,) ->[3,3] 크기 (1,2)

print(m1+m2)

tensor([4., 5.])


In [ ]:
# 2 x 1 vector + 1 x 2 Verctor
#브로드캐스팅은 자동으로 수행되므로 사용자는 나중에 원하는 결과가 나오지 않았더라도
#어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있습니다.
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]


In [ ]:
#행렬곱셉 .matmul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of m1: ', m1.shape) # 2 x 2
print('Shape of m2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of m1:  torch.Size([2, 2])
Shape of m2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
#원소 별 곱셈 .mul
#element-wise 곱셈: 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것
#서로 다른 크기의 행렬이 브로드캐스팅이 된 후에 element-wise 곱셈이 수행

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
#평균(mean)

t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
#dim=0이라는 것은 첫번째 차원을 의미합니다. 행렬에서 첫번째 차원은 '행'을 의미합니다. 그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 됩니다.
#다시 말해 행렬에서 '열'만을 남기겠다는 의미가 됩니다.

print(t.mean(dim=1))
#두번째 차원을 제거합니다. 즉, 열이 제거된 텐서가 되어야 합니다.

print(t.mean(dim=-1))
#마지막 차원을 제거한다는 의미이고, 결국 열의 차원을 제거한다는 의미와 같습니다. 그러므로 위와 출력 결과가 같습니다.

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
# 실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]

In [ ]:
#덧셈
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
#최대와 아그맥스(ArgMax):최대값을 가진 인덱스를 리턴
t = torch.FloatTensor([[5, 7], [1, 4]])
print(t)
print(t.max())
print(t.max(dim=0))
#max만 받아오기
print('Max:', t.max(dim=0)[0])
#인텍스만 받아오기
print('Argmax:', t.max(dim=0)[1])

tensor([[5., 7.],
        [1., 4.]])
tensor(7.)
torch.return_types.max(
values=tensor([5., 7.]),
indices=tensor([0, 0]))
Max: tensor([5., 7.])
Argmax: tensor([0, 0])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([7., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([7., 4.]),
indices=tensor([1, 1]))


In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape)
print(t.shape)

#3차원을 2차원으로 바꾸기
print(ft.view([-1,3]))
#-1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고,
#3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다.
print(ft.shape)

#3차원을 다른 형식의 3차원으로 바꾸기(크기 바꾸기)
print(ft.view(-1,3,1))
print(ft.view(-1,3,1).shape)

print(ft.view(3,-1,2))

torch.Size([2, 2, 3])
(2, 2, 3)
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([2, 2, 3])
tensor([[[ 0.],
         [ 1.],
         [ 2.]],

        [[ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.]]])
torch.Size([4, 3, 1])
tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]])


In [ ]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

ft1 = torch.FloatTensor([[0,1,2]])
print(ft1)
print(ft1.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
#열 제거 squeeze

ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

print('열제거 해보면')
print(ft.squeeze()) #열 제거
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
열제거 해보면
tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
#특정 위치에 1인 차원을 추가: unsqueeze

ft = torch.tensor([0,1,2]) #1차원 벡터
print(ft)
print(ft.shape)

print('---unsqueeze 써서 첫번째 차원에 1인 차원 추가---')
print(ft.unsqueeze(0)) #인덱스 0부터 시작, 0은 첫번째 차원을 의미
print(ft.unsqueeze(0).shape)

print('----view 써서 2차원으로 바꾸고 첫번째 차원은 1----')
print(ft.view(1,-1)) #인덱스 0부터 시작, 0은 첫번째 차원을 의미
print(ft.view(1,-1).shape)

print('----unsqueeze 써서 두번째 차원에 1인 차원 추가----')
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

print('----unsqueeze 써서 마지막 차원에 1인 차원 추가----')
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([0, 1, 2])
torch.Size([3])
---unsqueeze 써서 첫번째 차원에 1인 차원 추가---
tensor([[0, 1, 2]])
torch.Size([1, 3])
----view 써서 2차원으로 바꾸고 첫번째 차원은 1----
tensor([[0, 1, 2]])
torch.Size([1, 3])
----unsqueeze 써서 두번째 차원에 1인 차원 추가----
tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])
----unsqueeze 써서 마지막 차원에 1인 차원 추가----
tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


In [6]:
#텐서 연결

x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [8]:
#torch.cat([]) 사용해서 두 텐서 연결
#dim=0 첫 번째 차원 늘려라

print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [9]:
#dim=1 두 번째 차원 늘려라
print(torch.cat([x,y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [10]:
#스택킹
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [12]:
print(torch.cat([x,y,y], dim=0).shape)

torch.Size([6])


In [13]:
#스태킹 대신 cat 쓰려면 x, y, z를 (2,)크기에서 (1,2)로 바꿔줘야함
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [16]:
#0 또는 1로 채워진 텐서 만들기

x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

#ones_like: 동일한 크기지만 1으로만 값이 채워진 탠서 생성
print(torch.ones_like(x))

#zeros_like: 0으로만
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
#덮어쓰기 연산

x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.)) #곱하기 2를 수행한 결과 출력

print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


- 데이터사이언스 분야 한정으로 3차원 이상의 텐서는 그냥 다차원 행렬 또는 배열로 간주할 수 있습니다. 또한 주로 3차원 이상을 텐서라고 하긴 하지만, 1차원 벡터나 2차원인 행렬도 텐서라고 표현하기도 합니다. 같은 표현입니다. **벡터 = 1차원 텐서, 2차원 행렬 = 2차원 텐서, 그리고 3차원 텐서, 4차원 텐서, 5차원 텐서 등...**

훈련 데이터 하나의 크기를 256이라고 해봅시다. [3, 1, 2, 5, ...] 이런 숫자들의 나열이 256의 길이로 있다고 상상하면됩니다. 다시 말해 훈련 데이터 하나 = 벡터의 차원은 256입니다. 만약 이런 훈련 데이터의 개수가 3000개라고 한다면, 현재 전체 훈련 데이터의 크기는 3,000 × 256입니다. 행렬이니까 2D 텐서네요. 3,000개를 1개씩 꺼내서 처리하는 것도 가능하지만 컴퓨터는 훈련 데이터를 하나씩 처리하는 것보다 보통 덩어리로 처리합니다. 3,000개에서 64개씩 꺼내서 처리한다고 한다면 이 때 **batch size**를 64라고 합니다. 그렇다면 *컴퓨터가 한 번에 처리하는 2D 텐서의 크기는 (batch size × dim) = 64 × 256입니다.*

텐서의 크기(shape)를 표현할 때는 ,(컴마)를 쓰기도 하고 ×(곱하기)를 쓰기도 합니다. 예를 들어 2행 3열의 2D 텐서를 표현할 때 (2, 3)라고 하기도 하고 (2 × 3)이라고 하기도 합니다. (5, )의 형식은 (1 × 5)를 의미합니다.

훈련 데이터의 개수가 굉장히 많을 때, 컴퓨터가 한 번에 들고가서 처리할 양을 배치 크기(batch size)라고 합니다.

슬라이싱에 대한 다른 예제 : https://wikidocs.net/13